#ifndef AGENDAMODEL_GLOBAL_H
#define AGENDAMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AGENDAMODEL_LIBRARY)
#  define AGENDAMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AGENDAMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AGENDAMODEL_GLOBAL_H
